apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
      initContainers:
      - name: bootstrap
        image: "{{ .Values.image.repository }}:{{ include "operator.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["bootstrap"]
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
      - name: operator
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ required "A valid .Values.image.repository is required" .Values.image.repository }}:{{ include "operator.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
