replicaCount: 1

image:
  repository: pseudo-sealed-secrets
  pullPolicy: Never
  tag: "latest"

imagePullSecrets: []
nameOverride: "pseudo-sealed-secrets"
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 9999
  runAsUser: 9999
  runAsGroup: 9999

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources: {}

service:
  port: 8080

rbac:
  create: true

test:
  image: curlimages/curl:latest
